Qa python homework 1
alexqrid/2020-2-Atom-QA-Python-A-Gridin pull request #1
Opened 2020-09-26 22:39 UTC by alexqrid

#  Домашнее задание №
Прошу @snicks92 или @z1ll1 или @SK1995 проверить его.

Что было сделано:
*  Написаны автотесты для 5 структур данных(`int`, `string`, `list`, `set`, `dict`)
*  Оценено качество кода с помощью `pylint`, `flake8`, `pycodestyle`

2020-09-27 01:24 UTC, SK1995 requested changes
Очень приятно было видеть настроенный  CI в работе!
Оставил пару небольших комментариев по коду.

2020-09-27 01:24 UTC, SK1995 commented on QA-Python-homework-1/fixtures/fixtures.py
> +def get_int():
Кажется, что `get_int` и `get_string` можно было бы вынести в функции, а в фикстурах их использовать, для того, чтобы уменьшить дублирование кода.
Например так:
```python
def rand_int():
    return random.randint(1, 100)


def rand_str():
    return "".join(random.choices(string.ascii_letters,
                                  k=random.randint(1, 26)))


@pytest.fixture()
def get_int():
    yield rand_int()


@pytest.fixture()
def get_string():
    yield rand_str()


@pytest.fixture()
def get_list():
    yield [rand_int(), rand_str(), rand_int()]
```

2020-09-27 01:24 UTC, SK1995 commented on QA-Python-homework-1/tests/test_dict.py
> +        assert len(get_dict) != l1
Если это test_**update**, то тут лучше бы проверять, что в словарь действительно были занесены новые ключ и значение, а не просто что его длина изменилась.

2020-09-27 01:24 UTC, SK1995 commented on QA-Python-homework-1/tests/test_int.py
> +            assert get_int / 0
Тут не обязательно использовать `assert`.

2020-09-27 19:49 UTC, alexqrid commented on QA-Python-homework-1/tests/test_int.py
> +            assert get_int / 0
Да, невнимательность...

2020-09-27 19:49 UTC, alexqrid commented on QA-Python-homework-1/tests/test_dict.py
> +        assert len(get_dict) != l1
Понял.Спасибо.

2020-09-27 19:50 UTC, alexqrid commented on QA-Python-homework-1/fixtures/fixtures.py
> +def get_int():
А, да, думал ещё заменить на функции, но забыл. Косяк)

2020-10-07 19:15 UTC, SK1995 approved these changes

2020-10-07 19:16 UTC, SK1995 commented
Спасибо, все здорово, поставил максимальный балл за дз (4)

2020-10-07 19:16 UTC, merged